package principal;

import java.util.HashMap;
import java.util.Map;

public class Palavras {
	private Map<String, String> palavrasParaForca = new HashMap<String, String>();

	public void colocarPalavras() {
		palavrasParaForca.put("Esporte", "futebol");
		palavrasParaForca.put("Esporte1", "tênis");
		palavrasParaForca.put("Esporte2", "basquete");
		palavrasParaForca.put("Esporte3", "vôlei");
		palavrasParaForca.put("Esporte4", "golfe");
		palavrasParaForca.put("Esporte5", "boxe");
		palavrasParaForca.put("Esporte6", "ciclismo");
		palavrasParaForca.put("Esporte7", "natação");
		palavrasParaForca.put("Esporte8", "esqui");
		palavrasParaForca.put("Esporte9", "surfe");
		palavrasParaForca.put("Esporte10", "rúgbi");
		palavrasParaForca.put("Esporte11", "atletismo");
		palavrasParaForca.put("Esporte12", "hóquei");
		palavrasParaForca.put("Esporte13", "mma");
		palavrasParaForca.put("Esporte14", "xadrez");
		palavrasParaForca.put("Esporte15", "handebol");
		palavrasParaForca.put("Esporte16", "patinagem");
		palavrasParaForca.put("Esporte17", "escalada");
		palavrasParaForca.put("Esporte18", "badminton");
		palavrasParaForca.put("Esporte19", "esgrima");
		palavrasParaForca.put("Fruta0", "banana");
		palavrasParaForca.put("Animal0", "elefante");
		palavrasParaForca.put("País0", "brasil");
		palavrasParaForca.put("Profissões0", "médico");
		palavrasParaForca.put("Cor0", "vermelho");
		palavrasParaForca.put("Comida0", "pizza");
		palavrasParaForca.put("Esporte0", "futebol");
		palavrasParaForca.put("Cidade0", "paris");
		palavrasParaForca.put("Meio de Transporte0", "carro");
		palavrasParaForca.put("Instrumento Musical0", "violino");
		palavrasParaForca.put("Objeto0", "computador");
		palavrasParaForca.put("Sobremesa0", "bolo");
		palavrasParaForca.put("Personagem de Desenho0", "mickey");
		palavrasParaForca.put("Profissão0", "engenheiro");
		palavrasParaForca.put("País0", "japao");
		palavrasParaForca.put("Instrumento Musical0", "piano");
		palavrasParaForca.put("Comida0", "sushi");
		palavrasParaForca.put("Esporte21", "tenis");
		palavrasParaForca.put("Meio de Transporte01", "bicicleta");
		palavrasParaForca.put("Cor02", "azul");
		palavrasParaForca.put("Fruta0", "abacaxi");
		palavrasParaForca.put("Animal0", "girafa");
		palavrasParaForca.put("Cidade0", "roma");
		palavrasParaForca.put("Objeto", "televisao");
		palavrasParaForca.put("Profissões19", "advogado");
		palavrasParaForca.put("Comida", "hamburguer");
		palavrasParaForca.put("Frutas", "banana");
		palavrasParaForca.put("Frutas1", "maçã");
		palavrasParaForca.put("Frutas2", "uva");
		palavrasParaForca.put("Frutas3", "morango");
		palavrasParaForca.put("Frutas4", "abacaxi");
		palavrasParaForca.put("Frutas5", "laranja");
		palavrasParaForca.put("Frutas6", "mamão");
		palavrasParaForca.put("Frutas7", "melancia");
		palavrasParaForca.put("Frutas9", "kiwi");
		palavrasParaForca.put("Frutas10", "pêssego");
		palavrasParaForca.put("Frutas11", "pera");
		palavrasParaForca.put("Frutas12", "manga");
		palavrasParaForca.put("Frutas13", "cereja");
		palavrasParaForca.put("Frutas14", "ameixa");
		palavrasParaForca.put("Frutas15", "melão");
		palavrasParaForca.put("Frutas16", "abacate");
		palavrasParaForca.put("Frutas17", "pitanga");
		palavrasParaForca.put("Frutas18", "caqui");
		palavrasParaForca.put("Frutas19", "framboesa");
		palavrasParaForca.put("Profissões", "médico");
		palavrasParaForca.put("Profissões1", "engenheiro");
		palavrasParaForca.put("Profissões2", "professor");
		palavrasParaForca.put("Profissões3", "advogado");
		palavrasParaForca.put("Profissões4", "policial");
		palavrasParaForca.put("Profissões5", "piloto");
		palavrasParaForca.put("Profissões6", "cozinheiro");
		palavrasParaForca.put("Profissões7", "jornalista");
		palavrasParaForca.put("Profissões8", "músico");
		palavrasParaForca.put("Profissões9", "bombeiro");
		palavrasParaForca.put("Profissões10", "artista");
		palavrasParaForca.put("Profissões11", "dentista");
		palavrasParaForca.put("Profissões12", "arquiteto");
		palavrasParaForca.put("Profissões13", "cientista");
		palavrasParaForca.put("Profissões14", "programador");
		palavrasParaForca.put("Profissões15", "psicólogo");
		palavrasParaForca.put("Profissões16", "veterinário");
		palavrasParaForca.put("Profissões17", "designer");
		palavrasParaForca.put("Profissões18", "escritor");
		palavrasParaForca.put("objetos", "cadeira");
		palavrasParaForca.put("objetos1", "mesa");
		palavrasParaForca.put("objetos2", "telefone");
		palavrasParaForca.put("objetos3", "computador");
		palavrasParaForca.put("objetos4", "carro");
		palavrasParaForca.put("objetos5", "caneta");
		palavrasParaForca.put("objetos6", "relógio");
		palavrasParaForca.put("objetos7", "livro");
		palavrasParaForca.put("objetos8", "óculos");
		palavrasParaForca.put("objetos9", "chave");
		palavrasParaForca.put("objetos10", "copo");
		palavrasParaForca.put("objetos11", "câmera");
		palavrasParaForca.put("objetos12", "teclado");
		palavrasParaForca.put("objetos13", "sapato");
		palavrasParaForca.put("objetos14", "bola");
		palavrasParaForca.put("objetos15", "guarda-chuva");
		palavrasParaForca.put("objetos16", "carteira");
		palavrasParaForca.put("objetos17", "espelho");
		palavrasParaForca.put("objetos18", "garfo");
		palavrasParaForca.put("cidades", "paris");
		palavrasParaForca.put("cidades1", "nova york");
		palavrasParaForca.put("cidades2", "londres");
		palavrasParaForca.put("cidades3", "roma");
		palavrasParaForca.put("cidades4", "berlim");
		palavrasParaForca.put("cidades5", "tóquio");
		palavrasParaForca.put("cidades6", "rio de janeiro");
		palavrasParaForca.put("cidades7", "sydney");
		palavrasParaForca.put("cidades8", "moscou");
		palavrasParaForca.put("cidades9", "pequim");
		palavrasParaForca.put("cidades10", "cairo");
		palavrasParaForca.put("cidades11", "mumbai");
		palavrasParaForca.put("cidades12", "toronto");
		palavrasParaForca.put("cidades13", "amsterdã");
		palavrasParaForca.put("cidades14", "madri");
		palavrasParaForca.put("cidades15", "lisboa");
		palavrasParaForca.put("cidades16", "singapura");
		palavrasParaForca.put("cidades17", "dubai");
		palavrasParaForca.put("cidades18", "pequim");
		palavrasParaForca.put("cidades19", "istambul");
		palavrasParaForca.put("cores", "azul");
		palavrasParaForca.put("cores1", "vermelho");
		palavrasParaForca.put("cores2", "verde");
		palavrasParaForca.put("cores3", "amarelo");
		palavrasParaForca.put("cores4", "laranja");
		palavrasParaForca.put("cores5", "roxo");
		palavrasParaForca.put("cores6", "preto");
		palavrasParaForca.put("cores7", "branco");
		palavrasParaForca.put("cores8", "marrom");
		palavrasParaForca.put("cores9", "rosa");
		palavrasParaForca.put("cores10", "cinza");
		palavrasParaForca.put("cores11", "dourado");
		palavrasParaForca.put("cores12", "prateado");
		palavrasParaForca.put("cores13", "azul claro");
		palavrasParaForca.put("cores14", "verde claro");
		palavrasParaForca.put("cores15", "azul escuro");
		palavrasParaForca.put("cores16", "verde escuro");
		palavrasParaForca.put("cores17", "bege");
		palavrasParaForca.put("cores18", "vinho");
	}

	public Map<String, String> getPalavrasParaForca() {
		return palavrasParaForca;
	}

	public void setPalavrasParaForca(Map<String, String> palavrasParaForca) {
		this.palavrasParaForca = palavrasParaForca;
	}

}
